[[MiniFB]]
arch = "aarch64"
git-tree-sha1 = "7665f336a0852116a88ef49e7d6354a2103d24a7"
os = "macos"

    [[MiniFB.download]]
    sha256 = "e156ccdd9e1c5422792ef742432367cd75e4c6deadd8dac895c58eec7d73b022"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.aarch64-apple-darwin.tar.gz"
[[MiniFB]]
arch = "aarch64"
git-tree-sha1 = "044579223a00a2f2aed27aa2e30d94cfcfd01e1e"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "3a585c4f9ec6bebc3e902661058eeebbe586f1e18ddc509008cd18d4dabe7881"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.aarch64-linux-gnu.tar.gz"
[[MiniFB]]
arch = "aarch64"
git-tree-sha1 = "51582188b335e3031d70b6b1d638a73390fe2106"
libc = "musl"
os = "linux"

    [[MiniFB.download]]
    sha256 = "a2dba34fc995417d55d2f8e44129fdcc243842a885a724f71bc4aa032bfcef96"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.aarch64-linux-musl.tar.gz"
[[MiniFB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d058c62cc61c176c10ff2dda2c7660dec09457e2"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "9e351e1258279f569061bb172f315b108a750eb47833bd1a862a65023320f0ad"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.armv7l-linux-gnueabihf.tar.gz"
[[MiniFB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "710a8b47528790034094ad9978812fa14359ce61"
libc = "musl"
os = "linux"

    [[MiniFB.download]]
    sha256 = "bfa1f5854487d0f99c623825da569fb8aaf454813fbc44ae51eed6402b8fd4dd"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.armv7l-linux-musleabihf.tar.gz"
[[MiniFB]]
arch = "i686"
git-tree-sha1 = "ba2a1d894552f53b63b0266306134edc77bb06f1"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "cb81a06dac8b248be0ec97d789db8bba87eeea60abef4f30c1e9c2dec2f62310"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.i686-linux-gnu.tar.gz"
[[MiniFB]]
arch = "i686"
git-tree-sha1 = "e64c08113ff75fa56169f42339e52eea5c2aff78"
libc = "musl"
os = "linux"

    [[MiniFB.download]]
    sha256 = "7646eb69b816003facf2f46f6f9f22fa56be595d60b93784485b619ba57a0fa7"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.i686-linux-musl.tar.gz"
[[MiniFB]]
arch = "i686"
git-tree-sha1 = "08d80041cf3f15ff0431878d48be35b0dc434133"
os = "windows"

    [[MiniFB.download]]
    sha256 = "f907bf0dd0a35a04eb4631d9f6aee03ddaeea4647d54eef9a283f031c0c215fd"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.i686-w64-mingw32.tar.gz"
[[MiniFB]]
arch = "powerpc64le"
git-tree-sha1 = "e5e78148cf1386cbd88dcbbd6958710b7f3b7030"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "7166504766ccc48a27614d328802bfeb48d8c35bf8b9d57071d270b6da097e3f"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.powerpc64le-linux-gnu.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "bd1ecfa629e4e99961f87e24da7d0213742cebea"
os = "macos"

    [[MiniFB.download]]
    sha256 = "c3d43dbe927b996939c6aff3ef94d7740d9a9491fc8d90787b76f284e4573e95"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.x86_64-apple-darwin.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "3ff67dfb3bea8bd2656cd50107de8b91d6838a04"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "849d960f8ae169a00d715a87c6cd821e7157bd857039572fc9e73228d36c1144"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.x86_64-linux-gnu.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "7121ac5a16dd65e16c02ce22c2e713ff08def81b"
libc = "musl"
os = "linux"

    [[MiniFB.download]]
    sha256 = "60ca490fffd8ff541f97d27179266ddf9900098862c716dca23dbe3069d41baf"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.x86_64-linux-musl.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "44ac01d3272b7561a6f0f041a4adadc5a4347652"
os = "windows"

    [[MiniFB.download]]
    sha256 = "e3c2925b583de8fe4271cc8a77ee965c819cf1bd29d74952afa339d3787053be"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.1+0/MiniFB.v0.2.1.x86_64-w64-mingw32.tar.gz"
