[[MiniFB]]
arch = "aarch64"
git-tree-sha1 = "35b3f73acc5c0c732d9f6d46fe7f0eee7755bc06"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "bfa77236910c16230ac13932071a4cde908ebc254cd3dfefbaeb2f52b2fdf247"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.1.1+0/MiniFB.v0.1.1.aarch64-linux-gnu.tar.gz"
[[MiniFB]]
arch = "armv7l"
git-tree-sha1 = "750fdd1ddaea25b2a63e96e76044a54c4597d356"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "1cf13aa339d239c67bd5197654f380a0a88374077397f998801abbf02908eb8c"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.1.1+0/MiniFB.v0.1.1.armv7l-linux-gnueabihf.tar.gz"
[[MiniFB]]
arch = "i686"
git-tree-sha1 = "3dea6f09a4977edeaba2fbd12cc4d1b66a528fd6"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "00ef7a9e7f085cc5260cf2d87a371eecc63dd743f8f924337062e1691e8608db"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.1.1+0/MiniFB.v0.1.1.i686-linux-gnu.tar.gz"
[[MiniFB]]
arch = "i686"
git-tree-sha1 = "c5108653ca9cbe220dd74760f972e6fefd9072fa"
os = "windows"

    [[MiniFB.download]]
    sha256 = "937cabead16fd764df536cde2eb5c1e500de627cb475763601c523c151bf92b6"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.1.1+0/MiniFB.v0.1.1.i686-w64-mingw32.tar.gz"
[[MiniFB]]
arch = "powerpc64le"
git-tree-sha1 = "88eba5b6b5ea0bcbd4294affde16e6f801afce51"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "39e7bfe6b61361dcf4ac217d3cb03c99a5e9ac8003d870eb3b8a3ebf2c67e046"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.1.1+0/MiniFB.v0.1.1.powerpc64le-linux-gnu.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "53962d00d9d7e2866161b93b56876d32c12c911b"
os = "macos"

    [[MiniFB.download]]
    sha256 = "248e46ac49457c6b9588efdc0066f2cfe1d4292849f6de8943f4b54a3636df28"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.1.1+0/MiniFB.v0.1.1.x86_64-apple-darwin14.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "c7801ee196ecb415cb0716f9bebfb3350754f7e7"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "2214620472ee7800d58210ff31c0c0cb7d4d5430e476507e5331c891527d09db"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.1.1+0/MiniFB.v0.1.1.x86_64-linux-gnu.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "ef3e028a18df3f0c912428da059ece276573f012"
os = "windows"

    [[MiniFB.download]]
    sha256 = "bda584e4040263a7361bf79f58baf15342557c72e4de4f179f412a76c84a51ec"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.1.1+0/MiniFB.v0.1.1.x86_64-w64-mingw32.tar.gz"
