[[MiniFB]]
arch = "aarch64"
git-tree-sha1 = "07f7184f0300a7f6d8fc04b7b91ba6088b8ca2b8"
os = "macos"

    [[MiniFB.download]]
    sha256 = "d7ac4f8bd53cce6f72b6e505e5454e76b17c0e2884bcc1355c4cb402b9c28949"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.aarch64-apple-darwin.tar.gz"
[[MiniFB]]
arch = "aarch64"
git-tree-sha1 = "757e09a98c127e141e0a0a1d2f81824e870a57d3"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "c143bed75a27159e8b481a7b49e12700b127c2afbc19acd44b9f9306439daabf"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.aarch64-linux-gnu.tar.gz"
[[MiniFB]]
arch = "aarch64"
git-tree-sha1 = "3027bdcf5b9b1064bb1f609b0fc135991dd3cda4"
libc = "musl"
os = "linux"

    [[MiniFB.download]]
    sha256 = "f8d31d984519e1b6915ba16cde6b2c5b0189a8320f2f625169fca8068428c5b7"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.aarch64-linux-musl.tar.gz"
[[MiniFB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f3d9f82bf03eb1fc794ced15cd0345225c269ac"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "5b3bce348f9c98f70b82bb9d34480995fe4a485912535dbbbfa99772e8cd5c59"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[MiniFB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c412771700bc579f452e8063e13d06fec7a06d79"
libc = "musl"
os = "linux"

    [[MiniFB.download]]
    sha256 = "ba4df2cfd566fb373f4797c65cdf7c5f1604b2787c95dd858a37b77c99af33e0"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[MiniFB]]
arch = "i686"
git-tree-sha1 = "6a446e0bfb8ff7c8a09ab2c0d3839a45bc1a8d44"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "7100347940402bbed6895c80a5a4d57a2af5cfc525016bbd07c6c60bde21c7f8"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.i686-linux-gnu.tar.gz"
[[MiniFB]]
arch = "i686"
git-tree-sha1 = "dea7828060e3ded97ba76f8607eea7d43a564bfd"
libc = "musl"
os = "linux"

    [[MiniFB.download]]
    sha256 = "c6a67f41a48a0af86a25575074057f66fb7bc3c4c08a11b85c9ce121c032a5e0"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.i686-linux-musl.tar.gz"
[[MiniFB]]
arch = "i686"
git-tree-sha1 = "67408a5579fb02461404ba8c0bfeaf2e3c76643c"
os = "windows"

    [[MiniFB.download]]
    sha256 = "c287f7abc877fbb574630b8f48e10f3e34c8acb82e33e41a52bc1704b87573f5"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.i686-w64-mingw32.tar.gz"
[[MiniFB]]
arch = "powerpc64le"
git-tree-sha1 = "e53a5aba44fbea5e9d6b56a680d4474faf0ba33b"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "d26ebe14181ce75ba33293ea2390a49f66e45a2346fd92421e09e9f4704e30c3"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "9524d8e784811c69237ad1276352b96da896ad28"
os = "macos"

    [[MiniFB.download]]
    sha256 = "b649e170c2bcda499b64efc235e30f7c0e7b2c7480affe8b3f79f2301510547d"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.x86_64-apple-darwin.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "8511ddadd9b260988a122c0096fa51330ad9b805"
libc = "glibc"
os = "linux"

    [[MiniFB.download]]
    sha256 = "ef54624c65c7f0e83478ad1cf2f4c7876b8292388ed74c5dd80572a02305b388"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.x86_64-linux-gnu.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "4c9bcb7982474ac7b1b6071eada61f4db6f869b3"
libc = "musl"
os = "linux"

    [[MiniFB.download]]
    sha256 = "d71e57dd0b9fbd50a8449456ed0659ff011b3397291b8fccb48323b6c973925f"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.x86_64-linux-musl.tar.gz"
[[MiniFB]]
arch = "x86_64"
git-tree-sha1 = "336d4c10ff355af29f20137ddaff6ee12884d8f9"
os = "windows"

    [[MiniFB.download]]
    sha256 = "5c6cfdeaea633cc18e704bb02b731129d75ff8348a559ef0bd4309214c9346fb"
    url = "https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/download/MiniFB-v0.2.0+0/MiniFB.v0.2.0.x86_64-w64-mingw32.tar.gz"
