# Autogenerated wrapper script for MiniFB_jll for aarch64-apple-darwin
export libminifb

JLLWrappers.@generate_wrapper_header("MiniFB")
JLLWrappers.@declare_library_product(libminifb, "@rpath/libminifb.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libminifb,
        "lib/libminifb.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
