# Autogenerated wrapper script for MiniFB_jll for x86_64-w64-mingw32
export libminifb

JLLWrappers.@generate_wrapper_header("MiniFB")
JLLWrappers.@declare_library_product(libminifb, "libminifb.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libminifb,
        "bin\\libminifb.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
